name: devfest
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  firebase_remote_config: ^2.0.20
  firebase_analytics: ^9.3.8
  firebase_messaging: ^13.1.0
  storyly_flutter: ^1.26.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.1
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/devfest_circle_logo.png"